### PR TITLE
Note functionalities

### PR DESCRIPTION
**Pull request by AtulPant2704**
- Add & Edit Note
- Add, Restore and Delete From Archive
- Remove & Restore from Trash

`Note:- Color, Priority and Labels wont work as of now, I will work on it in upcoming PRs.`

### CODE REVIEW

**Comment by AnkurChunekar** [comment]
atul pr
You can have a fixed height to the content and set overflow property as hidden.

**Comment by AnkurChunekar** [comment]
atul pr 2
**suggestion**: Try to have consistent icon sizes.

**Comment by AtulPant2704** [comment]
> atul pr You can have a fixed height to the content and set overflow property as hidden.

Thanks for pointing it out, fixed that.

**Review by AnkurChunekar — APPROVED** [review]
- Services and Handlers are coded well.
- UI looks Good.
- Code looks neat and clean.

**Review by kart-c — COMMENTED** [review]
You also need to handle the same case @AnkurChunekar mentioned for the heading as well

**Review by kart-c — COMMENTED** [review]
You can handle image size for single card view

**Review by kart-c — APPROVED** [review]

**Pull request merged**
